apiVersion: v1
kind: Service
metadata:
  name: jmeter-slaves-svc
  labels:
    jmeter_mode: slave
spec:
  clusterIP: None
  ports:
    - port: 1099
      name: jm01
      targetPort: 1099
    - port: 50000
      name: jm02
      targetPort: 50000
  selector:
    jmeter_mode: slave