apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter
      jmeter_mode: master
  template:
    metadata:
      labels:
        app: jmeter
        jmeter_mode: master
        project: benchmark-manager
    spec:
      containers:
      - name: jmmaster
        image: thomasshibin09/jmeter-master:latest
        imagePullPolicy: Always
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - name: loadtest
            mountPath: /load_test
            subPath: "load_test"
        ports:
        - containerPort: 60000
        env:
        - name: HEAP
          value: "-Xms1G -Xmx12G"
        resources:
          limits:
            cpu: 8000m
            memory: 6Gi
          requests:
            cpu: 6000m
            memory: 4Gi
      terminationGracePeriodSeconds: 300
      volumes:
      - name: loadtest
        configMap:
         name: jmeter-load-test
