apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'connector'
        static_configs:
          - targets: ['${PROMETHEUS_TARGET}:9090']
